### ISSUE TITLE
cant add a tag to a file

### ISSUE THREAD

**Issue by shibumi** [botherder/viper#270] opened 2015-04-04 12:53 UTC
Hello,
I have some trouble with adding tags to a file: 
![lastimg](https://cloud.githubusercontent.com/assets/3833685/6992670/c62e5a70-dad9-11e4-93c4-08768feb4a88.png)

here is the filetree of my viper installation in /opt/viper: https://paste.archlinux.de/Pwu/
and this is the PKGBUILD for viper: https://paste.archlinux.de/KZm6/

I think there must be mistake in the user permissions in my installation

**Comment by deralexxx** [comment] 2015-04-04 16:51
I can confirm that "issue" it is due to the fact that the file is not stored in the database, if you call store before assign tags before the tags will be store.

Patch should be easy.

**Comment by shibumi** [comment] 2015-04-04 17:09
awesome. I will leave this issue open until its fixed

**Comment by SnakeByteIL** [comment] 2015-04-04 17:17
I kinda hate this issue as well, specially when downloading files from virustotal.

**Comment by kevthehermit** [comment] 2015-04-04 17:19
You will never be able to add tags until the file is stored in the DB no patch required. Just use the store command after opening. or add files using the store -f /path/to/files

**Comment by kevthehermit** [comment] 2015-04-04 17:20
Although will need to make that clearer in the output that it fails. so yeah bug :p

**Comment by deralexxx** [comment] 2015-04-04 17:35
That is what I meant with patch, proper exception handling for that but it is already in the todo within the commands file

**Comment by shibumi** [comment] 2015-04-04 17:36
btw guys when I delete a file why is the session still open?

**Comment by botherder** [comment] 2015-04-04 17:40
Closing this issue and reopening one with proper titling and description. Let's try to keep tickets clean please.

**Closed by botherder** 2015-04-04 17:40 UTC
